spring:
  application: 
    # 服务名
    name: wstro-web
  profiles:
    # 多环境配置
    active: local
  # 设置编码格式
  http:
    encoding:
      # 编码格式
      charset: UTF-8
      # 设置forceEncoding
      force: true
      # 是否开启
      enabled: true

# mybatis配置
        