spring:
  application: 
    # 服务名
    name: wstro-web
  profiles:
    # 多环境配置
    active: dev
  # 设置编码格式
  http:
    encoding:
      # 编码格式
      charset: UTF-8
      # 设置forceEncoding
      force: true
      # 是否开启
      enabled: true

# mybatis配置
mybatis:
  # 扫描映射文件
  mapper-locations:
  - classpath:mapper/*.xml
  # 配置扫描包的别名，主要是实体类包
  type-aliases-package: com.you.wstro.bean
  # 加载mybatis文件
  config-location: classpath:mybatis/mybatis-config.xml
  # 设置在控制台上打印sql语句
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        