server:
  port: 8081
  servlet:
    context-path: /wstro-web
  # 设置请求头的数据大小
  max-http-header-size: 404857
  # tomcat配置
  tomcat:
    # 设置字符编码
    uri-encoding: UTF-8
    # 最大连接数
    max-connections: 5000
    # 最小线程数
    min-spare-threads: 50
    # 最大线程数
    max-threads: 800
    # 队列长度
    accept-count: 1000
    # 服务器连接建立超时时间
    connection-timeout: 10000
    # 请求参数长度
    max-http-form-post-size: 30MB