server:
  port: 8080
  servlet:
    context-path: /wstro-server
  # 设置请求头的数据大小
  max-http-header-size: 404857
  # tomcat配置
  tomcat:
    # 设置字符编码
    uri-encoding: UTF-8
    # 最大连接数
    max-connections: 5000
    # 最小线程数
    min-spare-threads: 50
    # 最大线程数
    max-threads: 800
    # 队列长度
    accept-count: 1000
    # 服务器连接建立超时时间
    connection-timeout: 10000
    # 请求参数长度
    max-http-form-post-size: 30MB
    
# mysql数据源配置
spring:
  datasource:
    # JDBC连接Mysql6以上com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  # 发送邮件的相关配置
  mail:
    # 配置发送邮件服务器的地址
    host: smtp.qq.com
    # 配置邮件服务器的端口（465或587）
    port: 465
    # 配置发件人的账号
    username: jiashaoyou@qq.com
    # 配置用户的密码（即我们申请到的授权码）
    password: hgdmthggyrjzijjh
    # 发送邮件的协议
    protocol: smtp
    # 配置默认编码
    default-encoding: UTF-8
    properties:
      mail:
        debug: true # 开启 debug，这样方便开发者查看邮件发送日志
        smtp:
          auth: true
          ssl:
            enable: true # 开启SSL，QQ邮箱必须加此注解
          starttls: 
            enable: true
            required: true
#  配置日志输出级别
logging:
  # 指定logback配置文件的位置 
  config: classpath:logback-spring.xml
  # 文件日志要输出的路径
  path: C:/logs/wstro-server
  # 日志的输出级别
  level:
    root: info       
            
            